on:
  push:
    branches:
      - master

name: Deploy


env:
  IMAGE_VOT_ROMANIA: code4romania/vot-romania

jobs:
  build-dockerimage:
    name: Build Docker container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd src
          docker build . \
            --tag $IMAGE_VOT_ROMANIA:$GITHUB_SHA \
            --tag $IMAGE_VOT_ROMANIA:latest \
            --file Dockerfile

      - name: Upload Docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | \
          docker login \
            -u ${{ secrets.DOCKER_HUB_USERNAME }} \
            --password-stdin
          docker push -a $IMAGE_VOT_ROMANIA
